backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: public/images
public_folder: /images
collections:
  - name: "playlist"
    label: "Playlist"
    folder: "content/playlists"
    create: true
    slug: "{{year}}-{{month}}-{{day}}"
    fields:
      - { name: 'date', label: 'Publish Date', widget: 'datetime', format: 'YYYY-MM-DD' }
      - {label: "Body", name: "body", widget: "string"}
